### ISSUE TITLE
Document Unsupported Redis Read Replicas/Cluster (non-Sentinel)?

### ISSUE THREAD

**Issue by supertylerc** [nautobot/helm-charts#123]
The Bitnami Redis chart's [default architecture is `replication`](https://github.com/bitnami/charts/tree/master/bitnami/redis#default-master-replicas) (without Sentinel).  This chart, however, overrides that to set it to `standalone`.  This chart sets the Redis service name to the [headless service](https://github.com/nautobot/helm-charts/blob/9ebd710cdc22821c5e5e2ce67d1f43f2b319020e/charts/nautobot/templates/_helpers.tpl#L233-L248), which can't differentiate between write and read replicas.  The result is that when not using Sentinel but still wanting to have read replicas, you will get the following error:

```
redis.exceptions.ResponseError: Error running script (call to f_f6b93ec749d56aefa37c49bbc5e7a6eedd0d4ec3): @user_script:15: @user_script: 15: -READONLY You can't write against a read only replica.
```

The fix is to use the `*-redis-master` for writes and the `*-redis-replicas` service for reads.  However, it seems that Nautobot doesn't currently support it due to an upstream issue.  For those who are possibly not familiar with the implementation details of Nautobot, but who are familiar with the Bitnami Redis chart (or Redis in general), it might be helpful to have a notice that clustering/read replicas aren't supported by Nautobot (and therefore the functionality available in the Redis chart is unsupported).

**Comment by nniehoff** [comment]
I agree, we should fix this, but I'm curious your use case for the read replicas?  Are you using a custom nautobot config to read from the *replicas?

**Comment by supertylerc** [comment]
@nniehoff re: use case: No, no custom config for dealing with read replicas (afaik not currently possible, ref: suor/django-cacheops!35).  While I'd like that to be a supported thing, I think that's far outside of the scope of this Helm chart.

My concern was more an edge case: if someone doesn't realize that read replicas weren't supported _and_ was familiar with the Bitnami Redis chart _and_ chose to configure it as `architecture: replication`, it would have failed before !126.
