### ISSUE TITLE
Allow specify ingressClassName in the chart

### ISSUE THREAD

**Issue by apast0r** [nautobot/helm-charts#134]
Hi, I have different Ingress Objects on our k8s cluster for different environments:

```
$ kubectl get ingressClass 
NAME           CONTROLLER             PARAMETERS   AGE
nginx-pre      k8s.io/ingress-nginx   <none>       119d
nginx-qa       k8s.io/ingress-nginx   <none>       119d
```
The version of k8s is v1.20.11 and helm 3.8.
If I deploy nautobot using the provided helm chart, the ingress deploys, but doesn't work as expected due the missing spec [`ingressClassName`](https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource). 
If I edit the ingress object and add to it, then it work.

Would possible to add something like this in the ingress.yaml template:
```
{{- if .Values.ingress.enabled }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  [...]
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{end}}
  rules:
    [...]
```

**Comment by nniehoff** [comment]
@apast0r good catch thanks for mentioning it.  Simple fix released 1.2.3 of the chart.  Happy helming!
