### ISSUE TITLE
README feedback

### ISSUE THREAD

**Issue by tim-fiola** [nautobot/helm-charts#19]
I am a complete n00b to Helm charts.

I’d like to see the following in the README:
* What is a Helm chart?
* What is the use case for using Helm charts with Nautobot?
* What problem does this solution solve?
* Once this solution is installed, what then? How is it used?
* Screen shots of this solution in action
* The README says `This repo is intented to house helm charts for the Nautobot project. (Yes, today that is only the Nautobot chart, but we are ready for more)`.  Could there be multiple Helm charts for the Nautobot project?  Why would there need to be more than one?  What is the use case for more?

Having this info in the README will help a user who may be unfamiliar with Helm charts to determine if this solution can help them. Otherwise, this solution will only appeal to people who already understand the use case and already understand how a Helm chart adds value.

**Comment by nniehoff** [comment]
@tim-fiola did we get this one resolved?

**Comment by tim-fiola** [comment]
Yeah.  looks good!
