### ISSUE TITLE
FAQ section for README documentation

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/helm-charts#235]
Proposed addition to [README](https://github.com/nautobot/helm-charts/blob/develop/charts/nautobot/README.md):
- FAQ subsection
- Some FAQ items that might be useful to have

## FAQ

```markdown
Q. How do I list available helm chart releases for the repo?
A. Update the helm repo `$ helm repo update`, then run `$ helm search repo nautobot --versions`

Q. I don't see any pre-release helm charts from helm search repo
A. Add the `--devel` parameter eg: `$ helm search repo nautobot --versions --devel`
```

Thoughts:
- A table might work better
- Needs more items

**Comment by nniehoff** [comment]
@MeganerdDev I feel like these FAQs are really [helm](https://helm.sh/) specific FAQs and are included in their documentation
