### ISSUE TITLE
Bug: ServiceAccount not used in default config

### ISSUE THREAD

**Issue by BlackDark** [nautobot/helm-charts#260]
Reading the values one would assume that the created serviceaccount would be automatically be used in Nautobot.
But thats wrong. A check in the deployment avoids that those values are used: https://github.com/nautobot/helm-charts/blob/develop/charts/nautobot/templates/nautobot-deployment.yaml#L40

Ref:
- https://github.com/nautobot/helm-charts/blob/develop/charts/nautobot/values.yaml#L688

What did I expect?
- With default enabled serviceaccount creation that it would be linked to all required resources.

**Comment by nniehoff** [comment]
@BlackDark Thanks for this issue it will be fixed in #275 and released shortly in version 2.0.1
