### ISSUE TITLE
Enhancement: Allow additional properties in schema

### ISSUE THREAD

**Issue by BlackDark** [nautobot/helm-charts#287]
Not sure why the additional properties in the values are blocked but it would allow users to combine it with features like the dependencies in `helmfile` to allow building custom orderings if needed.
Ref: https://github.com/nautobot/helm-charts/blob/develop/charts/nautobot/values.schema.json#L6

Helmfile docs: https://helmfile.readthedocs.io/en/latest/advanced-features/#adding-dependencies-without-forking-the-chart

**Comment by nniehoff** [comment]
@BlackDark I'd like to understand what you are trying to do here a bit better.  That definition is only used by some other embedded schemas... We specifically disallow additional properties on most things specifically to prevent me from fat fingering things in most deployments it's really a safetfy thing.

**Comment by BlackDark** [comment]
@nniehoff like linked to the helmfile docs I would like to use a custom helm chart before deploying nautobot and therefore referencing it with the additional dependency. For example for creating secrets, configsmaps etc which will be used in the nautobot helm chart. But as soon as you add the dependency it will inject the `values.yml` from the dependency similar to the postgres, etc.. charts with its own "scope"/level in the file

```yaml
dependency:
	customValuesHere: ...
```

If this would where I could do a full rollout of nautobot with one command because it will be correctly ordered with the dependency stuff. But because of the schema this does not work and at the moment requires two commands to be executed.

```sh
# example
helmfile apply depdencies-for-nautobot
helmfile apply nautobot
```
