### ISSUE TITLE
Enclosed Network Nautobot 2.0.3 Install

### ISSUE THREAD

**Issue by Danmanny** [nautobot/helm-charts#336]
### Environment
* Nautobot version (Docker tag too if applicable): networktocode/nautobot:2.0.3-py3.10
* Python version: 3.10.13
* Database platform, version: bitnami/postgresql:15.3.0-debian-11-r7
* Middleware(s): xx

### Steps to Reproduce
1. Deploy Nautobot 2.0.3 via helm chart in an enclosed environment.

### Expected Behavior
I've deployed everything up to 1.6.1 in an enclosed environment but only ran into this issue with any 2.x.x versions.

### Observed Behavior
Get errors that the install failed with this error starting out.

Error Installation FAILED: values don't meet the specifications of the schema(s) in the following chart(s): timex.x.x.x.x nautobot: time x.x.x.x.x. "https://raw.githubusercontent.com/bitnami/charts/ba59192a4d0b28454f072903e5186d8bb2adf43f/bitnami/mariadb/values.schema.json": dial tcp: lookup raw.githubusercontnet.com on x.x.x.:53 no such host

And
Get "https://raw.githubusercontent.com/yannh/kuberenetes-json-schema/master/v1.23.12=standalone-strict/serviceport.json".
looks like everything thats in the values.schema.json pointing to an external directory.

**Comment by nniehoff** [comment]
@Danmanny can you try simply removing the `[values.schema.json](https://github.com/nautobot/helm-charts/blob/develop/charts/nautobot/values.schema.json)` file from the root of the repo in your offline deployment?

**Comment by Danmanny** [comment]
Way to resolve this issue.

1) Perform @nniehoff recommendation remove the values.schema.json file from the directory.
2) Replace values of the https://github.com/nautobot/helm-charts/tree/develop/charts/nautobot/chart.yaml
 - The below picture has the working values on the left and the default helm chart values on the right. 

![working-defaultvalues](https://github.com/nautobot/helm-charts/assets/77073542/05126179-3201-4376-9bc1-0696c2811088)
