### ISSUE TITLE
Charts configures the ServiceMonitor to scrape the `/api/plugins/capacity-metrics/rq-metrics` endpoint by default

### ISSUE THREAD

**Issue by ubajze** [nautobot/helm-charts#357]
The `rq-metrics` are no longer supported in the latest version of the capacity-metrics application.

I am using the default values for the `ServiceMonitor` configuration: https://github.com/nautobot/helm-charts/blob/fc581e61380983d24a67ac32afd3b2db3290ceeb/charts/nautobot/values.yaml#L932-L939

These values configure Prometheus to use the `/api/plugins/capacity-metrics/rq-metrics` endpoint, which is no longer supported in the latest versions of the capacity metrics application. We should remove this all together or make it optional: https://github.com/nautobot/helm-charts/blob/fc581e61380983d24a67ac32afd3b2db3290ceeb/charts/nautobot/templates/servicemonitor.yaml#L31

This setting generates a lot of errors like this:
```
[pid: 24|app: 0|req: 585/956] 100.68.137.171 () {32 vars in 610 bytes} [Mon Feb  5 09:47:06 2024] GET /api/plugins/capacity-metrics/rq-metrics => generated 24 bytes in 44 msecs (HTTP/1.1 404) 6 headers in 186 bytes (1 switches on core 1)
```

**Comment by bryanculver** [comment]
We should remove this monitor entirely.
