### ISSUE TITLE
Enhancement Automatic Roll of Deployments

### ISSUE THREAD

**Issue by rifen** [nautobot/helm-charts#440]
As a Nautobot Helm Deployment maintainer I am having inconsistent deployments depending on what values I change using `helm upgrade`. It isn't breaking but it can be annoying.

Found a recommendation from the Helm Docs:
https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

Seems like it would be straight forward to implement in this chart.

I couldn't find anywhere where it was utilizing this in any of the deployment charts eg. https://github.com/nautobot/helm-charts/blob/42413335dd84fe1e8fb6dc5cd11fdc27cda8c1f1/charts/nautobot/templates/celery-deployment.yaml#L8

But maybe it isn't needed 🤷🏻.

Submitting this for some extra 👀

**Comment by ubajze** [comment]
Thank you for opening an issue.

I want to make sure I understand the problem correctly. If you change something that only updates a ConfigMap, your Deployments are not restarted, and a new environmental variable is not injected into pods. Is that correct?

If this is the case, it is a reasonable ask.

In the meantime, you can probably deploy a tool like Reloader for example: https://github.com/stakater/Reloader

**Comment by rifen** [comment]
> Thank you for opening an issue.
> 
> I want to make sure I understand the problem correctly. If you change something that only updates a ConfigMap, your Deployments are not restarted, and a new environmental variable is not injected into pods. Is that correct?
> 
> If this is the case, it is a reasonable ask.
> 
> In the meantime, you can probably deploy a tool like Reloader for example: https://github.com/stakater/Reloader

Correct. My deployments never get the env var because my deployments don't get triggered.

I will take a look at that as well!
