### ISSUE TITLE
Liveness/Readiness probes failing on Celery worker pod

### ISSUE THREAD

**Issue by FabioSesta97** [nautobot/helm-charts#55]
After setting `nautobot.redis.ssl=true` and in the nautobot_config.py ` CELERY_REDIS_BACKEND_USE_SSL = {"ssl_cert_reqs": "none"}`, the Celery Worker fails the liveness/readiness probes without specifying an error. 
This make the pod unable to be on "Running 1/1"  state.

**Comment by nniehoff** [comment]
You may need to check why the pod is crashing, looking at `kubectl describe pod` looking specifically at `Last State`.  This may indicate OOMKilled or something similar in which case the `celeryWorker.resources` should be updated.  However, I believe this is more likely related to issue #57 can you please confirm after getting TLS working this is still occurring?

**Comment by FabioSesta97** [comment]
After getting TLS working the Liveness/Readiness probes  are working 👍.
