### ISSUE TITLE
Nautobot core/celery pods can't connect to Redis with SSL enabled

### ISSUE THREAD

**Issue by FabioSesta97** [nautobot/helm-charts#57]
After setting in the values.yaml `nautobot.redis.ssl=true` and in the nautobot_config.py `CELERY_REDIS_BACKEND_USE_SSL = {"ssl_cert_reqs": "none"}`, the pods still can't connect to Redis and have the following error:
`Cannot connect to rediss://:**@nautobot-redis-master:6379/0: Error 111 connecting to nautobot-redis-master:6379. Connection refused`

**Comment by nniehoff** [comment]
I'm hoping I can address this with #46 when we get there.

**Comment by nniehoff** [comment]
Please check the documentation provided in #77 and see if this addresses this issue.

**Comment by FabioSesta97** [comment]
I followed the documentation, the pods seems to be ok. Btw I still got this logs, defaulting to the insecure SSL behaviour. Is it normal? 
![MicrosoftTeams-image (19)](https://user-images.githubusercontent.com/49400382/143451583-c9ce732e-688e-4d25-a5e9-cd6c7c0eaecb.png)
![MicrosoftTeams-image (20)](https://user-images.githubusercontent.com/49400382/143451577-6398b76f-6baf-4ae2-aad1-ca831a5037f5.png)

**Comment by FabioSesta97** [comment]
Btw with this settings, make the Celery worker pass the Liveness/Readiness probes!

**Comment by nniehoff** [comment]
Ok, I updated the docs https://github.com/nautobot/helm-charts/tree/next/charts/nautobot#redis-tls there are some additional settings necessary in `nautobot_config.py`

**Comment by nniehoff** [comment]
Looks like this fixed the issue as discussed on slack, I'm closing this issue now.
